name: Sync Markdown to Notion

on:
  push:
    branches: [ main ]
    paths:
      - '*.md'
      - 'itineraries/*.md'
      - 'docs/*.md'
      - 'scripts/sync-markdown-to-notion.js'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Sync Markdown to Notion
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PARENT_PAGE_ID: ${{ secrets.NOTION_PARENT_PAGE_ID }}
      run: npm run sync

    - name: Success notification
      if: success()
      run: |
        echo "✅ Sincronização Markdown → Notion concluída!"
        echo "📄 Arquivos sincronizados: INDICE.md, itineraries/*.md"

    - name: Failure notification
      if: failure()
      run: echo "❌ Erro durante sincronização com Notion. Verifique os logs."
